@startuml
title Drone State Machine (Iteration 2)

[*] --> IDLE

IDLE --> EN_ROUTE : DISPATCH
EN_ROUTE --> DROPPING_AGENT : ARRIVED

DROPPING_AGENT --> RETURNING : TANK_EMPTY and fire_not_out
RETURNING --> IDLE : AT_BASE_REFILLED

DROPPING_AGENT --> IDLE : MISSION_COMPLETE
IDLE --> RETURNING : RETURN_TO_BASE_CMD

@enduml
